#include <stdint.h>
#ifndef CONST_H
#define CONST_H

//COMMON NODE HEADER LAYOUT
const uint32_t NODE_TYPE_SIZE = sizeof(uint8_t);
const uint32_t NODE_TYPE_OFFSET = 0;
const uint32_t IS_ROOT_SIZE = sizeof(uint8_t);
const uint32_t IS_ROOT_OFFSET = NODE_TYPE_SIZE;
const uint32_t PARENT_POINTER_SIZE = sizeof(uint32_t);
const uint32_t PARENT_POINTER_OFFSET = NODE_TYPE_SIZE + IS_ROOT_SIZE;
const uint32_t COMMON_NODE_HEADER_SIZE = NODE_TYPE_SIZE + IS_ROOT_SIZE + PARENT_POINTER_SIZE;

//ROOT NODE HEADER LAYOUT
const uint32_t ROOT_NODE_META_COLUMN_SIZE_SIZE = sizeof(uint32_t);
const uint32_t ROOT_NODE_META_COLUMN_SIZE_OFFSET = COMMON_NODE_HEADER_SIZE;
const uint32_t ROOT_NODE_META_COLUMN_NAME_SIZE = 30;
const uint32_t ROOT_NODE_META_COLUMN_TYPE_SIZE = sizeof(uint32_t);
const uint32_t ROOT_NODE_META_COLUMN_LENGTH_SIZE = sizeof(uint32_t);
const uint32_t ROOT_NODE_IS_PRIMARY_SIZE = sizeof(uint8_t);
const uint32_t ROOT_NODE_META_COLUMN_SIZE = ROOT_NODE_META_COLUMN_NAME_SIZE + ROOT_NODE_META_COLUMN_TYPE_SIZE  + ROOT_NODE_META_COLUMN_LENGTH_SIZE + ROOT_NODE_IS_PRIMARY_SIZE;
const uint32_t ROOT_NODE_META_COLUMN_OFFSET = ROOT_NODE_META_COLUMN_SIZE_OFFSET + ROOT_NODE_META_COLUMN_SIZE_SIZE;


//LEAF NODE HEADER LAYOUT
const uint32_t CELL_NUM_SIZE = sizeof(uint32_t);
const uint32_t CELL_NUM_OFFSET = COMMON_NODE_HEADER_SIZE;              
const uint32_t LEAF_NODE_NEXT_LEAF_SIZE = sizeof(uint32_t);
const uint32_t LEAF_NODE_NEXT_LEAF_OFFSET = CELL_NUM_OFFSET + CELL_NUM_SIZE;
const uint32_t LEAF_NODE_HEAD_SIZE = COMMON_NODE_HEADER_SIZE + CELL_NUM_SIZE + LEAF_NODE_NEXT_LEAF_SIZE;

//LEAF NODE BODY LAYOUT
const uint32_t LEAF_NODE_CELL_KEY_SIZE = sizeof(uint32_t);
const uint32_t LEAF_NODE_CELL_OFFSET = LEAF_NODE_HEAD_SIZE;

//INTERNAL NODE HEAD LAYOUT
const uint32_t KEYS_NUM_SIZE = sizeof(uint32_t);
const uint32_t KEYS_NUM_OFFSET = COMMON_NODE_HEADER_SIZE;
const uint32_t RIGHT_CHILD_SIZE = sizeof(uint32_t);
const uint32_t RIGHT_CHILD_OFFSET = KEYS_NUM_OFFSET + KEYS_NUM_SIZE;
const uint32_t INTERNAL_NODE_HEAD_SIZE = COMMON_NODE_HEADER_SIZE + KEYS_NUM_SIZE + RIGHT_CHILD_SIZE;

//INTERNAL NODE BODY LAYOUT
const uint32_t INTERNAL_NODE_CELL_KEY_SIZE = sizeof(uint32_t);
const uint32_t INTERNAL_NODE_CELL_CHILD_SIZE = sizeof(uint32_t);
const uint32_t INTERNAL_NODE_CELL_SIZE = INTERNAL_NODE_CELL_KEY_SIZE + INTERNAL_NODE_CELL_CHILD_SIZE;
const uint32_t INTERNAL_NODE_CELL_OFFSET = INTERNAL_NODE_HEAD_SIZE;
#endif
